Feature  FormShort and FormList viewcomponents
htkisui/QuikForm pull request #11
Opened 2024-01-28 14:31 UTC by Ellyria34

2024-01-29 09:38 UTC, 3l5a requested changes

2024-01-29 09:38 UTC, 3l5a commented on QuikForm.WebApp/Views/Shared/Components/FormList/FormListViewComponent.cs
> +    public async Task<IViewComponentResult> InvokeAsync(List<FormViewModel> forms)
Renommer forms en formViewModels, idem dans View() en dessous et attention à l'appel du VC dans l'index :)

2024-01-29 09:38 UTC, 3l5a commented on QuikForm.WebApp/Views/Sarah/Index.cshtml
> +        @await Component.InvokeAsync("FormList", new { forms = forms })
modifier l'appel du vc avec une balise

2024-01-29 09:38 UTC, 3l5a commented on QuikForm.WebApp/Views/Shared/Components/FormList/Default.cshtml
> +    };
`@model List<FormViewModel>` au lieu d'utiliser cette liste

2024-01-29 09:38 UTC, 3l5a commented on QuikForm.WebApp/Views/Shared/Components/FormList/Default.cshtml
> +    }
du coup `@form` devient `@Model`

2024-01-30 06:56 UTC, htkisui approved these changes

2024-01-30 06:56 UTC, closed without merging